# creazione container 
FROM python:3.10-alpine
ADD server.py .
RUN ls -l
# installazione flask sul container 
RUN pip install flask
# aggiunta pagine html  create sul computer fisico sul container 
RUN mkdir templates
ADD ./templates/index.html .templates
ADD ./templates/index2.html .templates
# mapping tra le porte
CMD ["python","./server.py"] 




